apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: prometheus
spec:
  rules:
  - host: GRAFANA_DNS
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
